#!/bin/sh

file="/workspace/*tmc/WIP2"
file2="/workspace/*tmc/WIP"

if ls $file >/dev/null 2>&1;
then
        echo "Breathecam script was stopped in a spot that requires non-trivial work to recover."
else
        rm $file2
fi

exit 0
