source 'https://rubygems.org'

gem 'rails', '3.2.22.5'

gem 'rake', '~> 12.2.1'

# Last version that works with ruby 1.9.3
gem 'rack-cache', '1.7.1'

gem 'sass', '~> 3.4.25'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'exiftool'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

# Needed for precompiling assets
# Apparently installing Node.js also solves this.
gem 'execjs'
gem 'therubyracer', :platforms => :ruby

gem 'jquery-rails'

#gem 'nokogiri'
gem 'rb-readline'

# webrick is a standard ruby library, but using it in gem form
# stops the following message from displaying in the console
# during development.
# 'WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true'
group :development do
  gem 'webrick', '~> 1.3.1'
end
