source 'https://rubygems.org'

gem 'rails', '3.2.18'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

# Needed for precompiling assets
# Apparently installing Node.js also solves this.
gem 'execjs'
gem 'therubyracer', :platforms => :ruby

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# webrick is a standard ruby library, but using it in gem form
# stops the following message from displaying in the console
# during development.
# 'WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true'
group :development do
  gem 'webrick', '~> 1.3.1'
end
