/**
 The MIT License

 Copyright (c) 2010 Daniel Park (http://metaweb.com, http://postmessage.freebaseapps.com)

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 **/
var NO_JQUERY={};
(function(f,m,t){if(!("console"in f)){var r=f.console={};r.log=r.warn=r.error=r.debug=function(){}}m===NO_JQUERY&&(m={fn:{},extend:function(){for(var a=arguments[0],b=1,c=arguments.length;b<c;b++){var e=arguments[b],g;for(g in e)a[g]=e[g]}return a}});m.fn.pm=function(){console.log("usage: \nto send:    $.pm(options)\nto receive: $.pm.bind(type, fn, [origin])");return this};m.pm=f.pm=function(a){c.send(a)};m.pm.bind=f.pm.bind=function(a,b,d,e,g){c.bind(a,b,d,e,!0===g)};m.pm.unbind=f.pm.unbind=function(a,
b){c.unbind(a,b)};m.pm.origin=f.pm.origin=null;m.pm.poll=f.pm.poll=200;var c={send:function(a){a=m.extend({},c.defaults,a);var b=a.target;if(a.target)if(a.type){var d={data:a.data,type:a.type};a.success&&(d.callback=c._callback(a.success));a.error&&(d.errback=c._callback(a.error));"postMessage"in b&&!a.hash?(c._bind(),b.postMessage(JSON.stringify(d),a.origin||"*")):(c.hash._bind(),c.hash.send(a,d))}else console.warn("postmessage type required");else console.warn("postmessage target window required")},
bind:function(a,b,d,e,g){c._replyBind(a,b,d,e,g)},_replyBind:function(a,b,d,e,g){"postMessage"in f&&!e?c._bind():c.hash._bind();e=c.data("listeners.postmessage");e||(e={},c.data("listeners.postmessage",e));var n=e[a];n||(n=[],e[a]=n);n.push({fn:b,callback:g,origin:d||m.pm.origin})},unbind:function(a,b){var d=c.data("listeners.postmessage");if(d)if(a)if(b){var e=d[a];if(e){for(var g=[],n=0,k=e.length;n<k;n++){var h=e[n];h.fn!==b&&g.push(h)}d[a]=g}}else delete d[a];else for(n in d)delete d[n]},data:function(a,
b){return b===t?c._data[a]:c._data[a]=b},_data:{},_CHARS:"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),_random:function(){for(var a=[],b=0;32>b;b++)a[b]=c._CHARS[0|32*Math.random()];return a.join("")},_callback:function(a){var b=c.data("callbacks.postmessage");b||(b={},c.data("callbacks.postmessage",b));var d=c._random();b[d]=a;return d},_bind:function(){c.data("listening.postmessage")||(f.addEventListener?f.addEventListener("message",c._dispatch,!1):f.attachEvent&&f.attachEvent("onmessage",
c._dispatch),c.data("listening.postmessage",1))},_dispatch:function(a){try{var b=JSON.parse(a.data)}catch(d){console.warn("postmessage data invalid json: ",d);return}if(b.type){var e=(c.data("callbacks.postmessage")||{})[b.type];if(e)e(b.data);else for(var e=(c.data("listeners.postmessage")||{})[b.type]||[],g=0,n=e.length;g<n;g++){var k=function(g){b.callback&&c.send({target:a.source,data:g,type:b.callback})},h=e[g];if(h.origin&&"*"!==h.origin&&a.origin!==h.origin)console.warn("postmessage message origin mismatch",
a.origin,h.origin),b.errback&&c.send({target:a.source,data:{message:"postmessage origin mismatch",origin:[a.origin,h.origin]},type:b.errback});else try{h.callback?h.fn(b.data,k,a):k(h.fn(b.data,a))}catch(l){if(b.errback)c.send({target:a.source,data:l,type:b.errback});else throw l;}}}else console.warn("postmessage message type required")},hash:{send:function(a,b){var d=a.target,e=a.url;if(e){var e=c.hash._url(e),g,n=c.hash._url(f.location.href);if(f==d.parent)g="parent";else try{for(var k=0,h=parent.frames.length;k<
h;k++)if(parent.frames[k]==f){g=k;break}}catch(l){g=f.name}null==g?console.warn("postmessage windows must be direct parent/child windows and the child must be available through the parent window.frames list"):(g={"x-requested-with":"postmessage",source:{name:g,url:n},postmessage:b},n="#x-postmessage-id="+c._random(),d.location=e+n+encodeURIComponent(JSON.stringify(g)))}else console.warn("postmessage target window url is required")},_regex:/^\#x\-postmessage\-id\=(\w{32})/,_regex_len:50,_bind:function(){c.data("polling.postmessage")||
(setInterval(function(){var a=""+f.location.hash,b=c.hash._regex.exec(a);b&&(b=b[1],c.hash._last!==b&&(c.hash._last=b,c.hash._dispatch(a.substring(c.hash._regex_len))))},m.pm.poll||200),c.data("polling.postmessage",1))},_dispatch:function(a){if(a){try{if(a=JSON.parse(decodeURIComponent(a)),!("postmessage"===a["x-requested-with"]&&a.source&&null!=a.source.name&&a.source.url&&a.postmessage))return}catch(b){return}var d=a.postmessage,e=(c.data("callbacks.postmessage")||{})[d.type];if(e)e(d.data);else{var g;
g="parent"===a.source.name?f.parent:f.frames[a.source.name];for(var e=(c.data("listeners.postmessage")||{})[d.type]||[],n=0,k=e.length;n<k;n++){var h=function(b){d.callback&&c.send({target:g,data:b,type:d.callback,hash:!0,url:a.source.url})},l=e[n];if(l.origin){var m=/https?\:\/\/[^\/]*/.exec(a.source.url)[0];if("*"!==l.origin&&m!==l.origin){console.warn("postmessage message origin mismatch",m,l.origin);d.errback&&c.send({target:g,data:{message:"postmessage origin mismatch",origin:[m,l.origin]},type:d.errback,
hash:!0,url:a.source.url});continue}}try{l.callback?l.fn(d.data,h):h(l.fn(d.data))}catch(s){if(d.errback)c.send({target:g,data:s,type:d.errback,hash:!0,url:a.source.url});else throw s;}}}}},_url:function(a){return(""+a).replace(/#.*$/,"")}}};m.extend(c,{defaults:{target:null,url:null,type:null,data:null,success:null,error:null,origin:"*",hash:!1}})})(this,"undefined"===typeof jQuery?NO_JQUERY:jQuery);"JSON"in window&&window.JSON||(JSON={});
(function(){function f(a){return 10>a?"0"+a:a}function m(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=d[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function t(c,d){var k,h,l,f,s=a,q,p=d[c];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(c));"function"===typeof e&&(p=e.call(d,c,p));switch(typeof p){case "string":return m(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";a+=b;q=[];if("[object Array]"===Object.prototype.toString.apply(p)){f=p.length;for(k=0;k<f;k+=1)q[k]=t(k,p)||"null";l=0===q.length?"[]":a?"[\n"+a+q.join(",\n"+a)+"\n"+s+"]":"["+q.join(",")+"]";a=s;return l}if(e&&"object"===typeof e)for(f=e.length,k=0;k<f;k+=1)h=e[k],"string"===typeof h&&(l=t(h,p))&&q.push(m(h)+(a?": ":":")+l);else for(h in p)Object.hasOwnProperty.call(p,h)&&(l=t(h,p))&&q.push(m(h)+(a?": ":":")+l);l=0===q.length?"{}":a?"{\n"+a+q.join(",\n"+a)+"\n"+
s+"}":"{"+q.join(",")+"}";a=s;return l}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(a){return this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z"},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var r=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,b,d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},e;"function"!==typeof JSON.stringify&&(JSON.stringify=function(c,d,k){var h;b=a="";if("number"===typeof k)for(h=0;h<k;h+=1)b+=" ";else"string"===typeof k&&(b=k);if((e=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return t("",{"":c})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function c(a,d){var e,g,f=a[d];if(f&&"object"===typeof f)for(e in f)Object.hasOwnProperty.call(f,e)&&(g=c(f,e),void 0!==g?f[e]=g:delete f[e]);return b.call(a,d,f)}var d;r.lastIndex=0;r.test(a)&&(a=a.replace(r,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,
"")))return d=eval("("+a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();